// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZagrosRealState.Data.Models.DbContext;

namespace ZagrosRealState.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200911211215_Add_Update_Database")]
    partial class Add_Update_Database
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ZagrosRealState.Data.Models.Data.ApplicationRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("ZagrosRealState.Data.Models.Data.ApplicationUsers", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment", b =>
                {
                    b.Property<int>("Apartment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apartment_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Anbari")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Asansor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_CodeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Apartment_DateTakhliyeh")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Apartment_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("Apartment_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Ejareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Enshaaab_Aab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Enshaaab_Baargh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Enshaaab_Gaaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Enshaaab_Telephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_HagheCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_HagheCharge_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Apartment_Image")
                        .HasColumnType("image");

                    b.Property<string>("Apartment_Metrazh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_MojerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_MojerTell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_NumBolook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_NumKhab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_NumVahed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_PriceEjareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_PriceRahn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Apartment_PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Apartment_Shoofazh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_StatusEnshaaab")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_StatusRahnAparteman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Tabaghe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Takhliyeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apartment_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Apartment_UserId")
                        .HasColumnType("int");

                    b.HasKey("Apartment_Id");

                    b.ToTable("Apartments");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_Anbari", b =>
                {
                    b.Property<int>("LST_AnbariAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_AnbariAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_AnbariAPId");

                    b.ToTable("Apartment_LST_Anbaris");

                    b.HasData(
                        new
                        {
                            LST_AnbariAPId = 1,
                            LST_AnbariAPName = "دارد"
                        },
                        new
                        {
                            LST_AnbariAPId = 2,
                            LST_AnbariAPName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_ApartemanStatus", b =>
                {
                    b.Property<int>("LST_ApartemanStatusAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_ApartemanStatusAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_ApartemanStatusAPId");

                    b.ToTable("Apartment_LST_ApartemanStatuses");

                    b.HasData(
                        new
                        {
                            LST_ApartemanStatusAPId = 1,
                            LST_ApartemanStatusAPName = "رهن شده"
                        },
                        new
                        {
                            LST_ApartemanStatusAPId = 2,
                            LST_ApartemanStatusAPName = "تخلیه شده"
                        },
                        new
                        {
                            LST_ApartemanStatusAPId = 3,
                            LST_ApartemanStatusAPName = "اجاره شده"
                        },
                        new
                        {
                            LST_ApartemanStatusAPId = 4,
                            LST_ApartemanStatusAPName = "به فروش رسیده"
                        },
                        new
                        {
                            LST_ApartemanStatusAPId = 5,
                            LST_ApartemanStatusAPName = "تحت تملک می باشد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_Asansor", b =>
                {
                    b.Property<int>("LST_AsansorAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_AsansorAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_AsansorAPId");

                    b.ToTable("Apartment_LST_Asansors");

                    b.HasData(
                        new
                        {
                            LST_AsansorAPId = 1,
                            LST_AsansorAPName = "دارد"
                        },
                        new
                        {
                            LST_AsansorAPId = 2,
                            LST_AsansorAPName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_Ejareh", b =>
                {
                    b.Property<int>("LST_EjarehAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_EjarehAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_EjarehAPId");

                    b.ToTable("Apartment_LST_Ejarehs");

                    b.HasData(
                        new
                        {
                            LST_EjarehAPId = 1,
                            LST_EjarehAPName = "دارد"
                        },
                        new
                        {
                            LST_EjarehAPId = 2,
                            LST_EjarehAPName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_EmkanatSatus", b =>
                {
                    b.Property<int>("LST_EmkanatSatusAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Entity_ApartemanApartment_Id")
                        .HasColumnType("int");

                    b.Property<string>("LST_EmkanatSatusAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_EmkanatSatusAPId");

                    b.HasIndex("Entity_ApartemanApartment_Id");

                    b.ToTable("Apartment_LST_EmkanatSatus");

                    b.HasData(
                        new
                        {
                            LST_EmkanatSatusAPId = 1,
                            LST_EmkanatSatusAPName = "کلیه امکانات مشترک"
                        },
                        new
                        {
                            LST_EmkanatSatusAPId = 2,
                            LST_EmkanatSatusAPName = "کلیه امکانات مستقل"
                        },
                        new
                        {
                            LST_EmkanatSatusAPId = 3,
                            LST_EmkanatSatusAPName = "فاقد هر گونه امکانات"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_HagheCharge", b =>
                {
                    b.Property<int>("LST_HagheChargeAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_HagheChargeAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_HagheChargeAPId");

                    b.ToTable("Apartment_LST_HagheCharges");

                    b.HasData(
                        new
                        {
                            LST_HagheChargeAPId = 1,
                            LST_HagheChargeAPName = "دارد"
                        },
                        new
                        {
                            LST_HagheChargeAPId = 2,
                            LST_HagheChargeAPName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_NumAB", b =>
                {
                    b.Property<int>("LST_NumABAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_NumABAP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_NumABAPId");

                    b.ToTable("Apartment_LST_NumABs");

                    b.HasData(
                        new
                        {
                            LST_NumABAPId = 1,
                            LST_NumABAP = "دارد"
                        },
                        new
                        {
                            LST_NumABAPId = 2,
                            LST_NumABAP = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_NumBargh", b =>
                {
                    b.Property<int>("LST_NumBarghAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_NumBarghAP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_NumBarghAPId");

                    b.ToTable("Apartment_LST_NumBarghs");

                    b.HasData(
                        new
                        {
                            LST_NumBarghAPId = 1,
                            LST_NumBarghAP = "دارد"
                        },
                        new
                        {
                            LST_NumBarghAPId = 2,
                            LST_NumBarghAP = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_NumGAZ", b =>
                {
                    b.Property<int>("LST_NumGAZAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_NumGAZAP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_NumGAZAPId");

                    b.ToTable("Apartment_LST_NumGAZs");

                    b.HasData(
                        new
                        {
                            LST_NumGAZAPId = 1,
                            LST_NumGAZAP = "دارد"
                        },
                        new
                        {
                            LST_NumGAZAPId = 2,
                            LST_NumGAZAP = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_NumKhab", b =>
                {
                    b.Property<int>("LST_NumKhabAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_NumKhabAP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_NumKhabAPId");

                    b.ToTable("Apartment_LST_NumKhabs");

                    b.HasData(
                        new
                        {
                            LST_NumKhabAPId = 1,
                            LST_NumKhabAP = "1"
                        },
                        new
                        {
                            LST_NumKhabAPId = 2,
                            LST_NumKhabAP = "2"
                        },
                        new
                        {
                            LST_NumKhabAPId = 3,
                            LST_NumKhabAP = "3"
                        },
                        new
                        {
                            LST_NumKhabAPId = 4,
                            LST_NumKhabAP = "4"
                        },
                        new
                        {
                            LST_NumKhabAPId = 5,
                            LST_NumKhabAP = "5"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_NumTELL", b =>
                {
                    b.Property<int>("LST_NumTELLAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_NumTELLAP")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_NumTELLAPId");

                    b.ToTable("Apartment_LST_NumTELLs");

                    b.HasData(
                        new
                        {
                            LST_NumTELLAPId = 1,
                            LST_NumTELLAP = "دارد"
                        },
                        new
                        {
                            LST_NumTELLAPId = 2,
                            LST_NumTELLAP = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_Parking", b =>
                {
                    b.Property<int>("LST_ParkingAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_ParkingAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_ParkingAPId");

                    b.ToTable("Apartment_LST_Parkings");

                    b.HasData(
                        new
                        {
                            LST_ParkingAPId = 1,
                            LST_ParkingAPName = "دارد"
                        },
                        new
                        {
                            LST_ParkingAPId = 2,
                            LST_ParkingAPName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_Shoofazh", b =>
                {
                    b.Property<int>("LST_ShoofazhAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_ShoofazhAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_ShoofazhAPId");

                    b.ToTable("Apartment_LST_Shoofazhs");

                    b.HasData(
                        new
                        {
                            LST_ShoofazhAPId = 1,
                            LST_ShoofazhAPName = "دارد"
                        },
                        new
                        {
                            LST_ShoofazhAPId = 2,
                            LST_ShoofazhAPName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_Takhliyeh", b =>
                {
                    b.Property<int>("LST_TakhliyehAPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LST_TakhliyehAPName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LST_TakhliyehAPId");

                    b.ToTable("Apartment_LST_Takhliyehs");

                    b.HasData(
                        new
                        {
                            LST_TakhliyehAPId = 1,
                            LST_TakhliyehAPName = "تخلیه فوری"
                        },
                        new
                        {
                            LST_TakhliyehAPId = 2,
                            LST_TakhliyehAPName = "تخلیه شده"
                        },
                        new
                        {
                            LST_TakhliyehAPId = 3,
                            LST_TakhliyehAPName = "در حال تخلیه"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.ByeAndSell", b =>
                {
                    b.Property<int>("ByeAndSell_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ByeAndSellCode_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_CodePosty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ByeAndSell_DatePublish")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ByeAndSell_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("ByeAndSell_Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ByeAndSell_Image")
                        .HasColumnType("image");

                    b.Property<string>("ByeAndSell_JahateMoameleh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_Moshakhasat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_TypeEstefadeh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_TypeKarbary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_TypeMoredeMoameleh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByeAndSell_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ByeAndSell_UserId")
                        .HasColumnType("int");

                    b.HasKey("ByeAndSell_Id");

                    b.ToTable("ByeAndSells");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.ByeAndSell_LST_JahatMoamele", b =>
                {
                    b.Property<int>("ByeAndSell_LST_JahatMoameleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ByeAndSell_LST_JahatMoameleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ByeAndSell_LST_JahatMoameleId");

                    b.ToTable("ByeAndSell_LST_JahatMoameles");

                    b.HasData(
                        new
                        {
                            ByeAndSell_LST_JahatMoameleId = 1,
                            ByeAndSell_LST_JahatMoameleName = "خرید"
                        },
                        new
                        {
                            ByeAndSell_LST_JahatMoameleId = 2,
                            ByeAndSell_LST_JahatMoameleName = "فروش"
                        },
                        new
                        {
                            ByeAndSell_LST_JahatMoameleId = 3,
                            ByeAndSell_LST_JahatMoameleName = "معاوضه"
                        },
                        new
                        {
                            ByeAndSell_LST_JahatMoameleId = 4,
                            ByeAndSell_LST_JahatMoameleName = "سایر"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.ByeAndSell_LST_Karbary", b =>
                {
                    b.Property<int>("ByeAndSell_LST_TypeKarbaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ByeAndSell_LST_TypeKarbaryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ByeAndSell_LST_TypeKarbaryId");

                    b.ToTable("ByeAndSell_LST_Karbaries");

                    b.HasData(
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 1,
                            ByeAndSell_LST_TypeKarbaryName = "مسکونی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 2,
                            ByeAndSell_LST_TypeKarbaryName = "تجاری"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 3,
                            ByeAndSell_LST_TypeKarbaryName = "آموزشی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 4,
                            ByeAndSell_LST_TypeKarbaryName = "صنعتی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 5,
                            ByeAndSell_LST_TypeKarbaryName = "ورزشی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 6,
                            ByeAndSell_LST_TypeKarbaryName = "بهداشتی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 7,
                            ByeAndSell_LST_TypeKarbaryName = "خدماتی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 8,
                            ByeAndSell_LST_TypeKarbaryName = "دامداری"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 9,
                            ByeAndSell_LST_TypeKarbaryName = "مرغداری"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 10,
                            ByeAndSell_LST_TypeKarbaryName = "دامپروری"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 11,
                            ByeAndSell_LST_TypeKarbaryName = "گلخانه"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 12,
                            ByeAndSell_LST_TypeKarbaryName = "پرورش ماهی"
                        },
                        new
                        {
                            ByeAndSell_LST_TypeKarbaryId = 13,
                            ByeAndSell_LST_TypeKarbaryName = "باغ و باغچه"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.ByeAndSell_LST_MoredeMoameleh", b =>
                {
                    b.Property<int>("ByeAndSell_LST_MoredeMoameleh_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ByeAndSell_LST_MoredeMoameleh_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ByeAndSell_LST_MoredeMoameleh_Id");

                    b.ToTable("ByeAndSell_LST_MoredeMoamelehs");

                    b.HasData(
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 1,
                            ByeAndSell_LST_MoredeMoameleh_Name = "یک دستگاه آپارتمان"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 2,
                            ByeAndSell_LST_MoredeMoameleh_Name = "یک باب مغازه تجاری"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 3,
                            ByeAndSell_LST_MoredeMoameleh_Name = "یک واحد تجاری"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 4,
                            ByeAndSell_LST_MoredeMoameleh_Name = "یک واحد تجاری دوبلکس"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 5,
                            ByeAndSell_LST_MoredeMoameleh_Name = "یک واحد آپارتمان"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 6,
                            ByeAndSell_LST_MoredeMoameleh_Name = "یک قطعه زمین"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 7,
                            ByeAndSell_LST_MoredeMoameleh_Name = "باغ شهر"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 8,
                            ByeAndSell_LST_MoredeMoameleh_Name = "منزل ویلایی"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 9,
                            ByeAndSell_LST_MoredeMoameleh_Name = "قطعه انباری"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 10,
                            ByeAndSell_LST_MoredeMoameleh_Name = "قطعه پارکینگ"
                        },
                        new
                        {
                            ByeAndSell_LST_MoredeMoameleh_Id = 11,
                            ByeAndSell_LST_MoredeMoameleh_Name = "دستگاه سوله"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Cities", b =>
                {
                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProvinceID")
                        .HasColumnType("int");

                    b.HasKey("CityID");

                    b.HasIndex("ProvinceID");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Customers", b =>
                {
                    b.Property<int>("Customers_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CitiesCityID")
                        .HasColumnType("int");

                    b.Property<string>("Customers_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customers_CodeMelli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Customers_DatePublish")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Customers_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("Customers_Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Customers_Image")
                        .HasColumnType("image");

                    b.Property<string>("Customers_Job")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customers_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customers_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customers_Tell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customers_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Customers_UserId")
                        .HasColumnType("int");

                    b.HasKey("Customers_Id");

                    b.HasIndex("CitiesCityID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Customers_LST_JOB", b =>
                {
                    b.Property<int>("Customers_LST_JOBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Customers_LST_JOBName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Customers_LST_JOBId");

                    b.ToTable("Customers_LST_JOBs");

                    b.HasData(
                        new
                        {
                            Customers_LST_JOBId = 1,
                            Customers_LST_JOBName = "دولتی"
                        },
                        new
                        {
                            Customers_LST_JOBId = 2,
                            Customers_LST_JOBName = "آزاد"
                        },
                        new
                        {
                            Customers_LST_JOBId = 3,
                            Customers_LST_JOBName = "بیکار"
                        },
                        new
                        {
                            Customers_LST_JOBId = 4,
                            Customers_LST_JOBName = "دانشجو"
                        },
                        new
                        {
                            Customers_LST_JOBId = 5,
                            Customers_LST_JOBName = "استاد دانشگاه"
                        },
                        new
                        {
                            Customers_LST_JOBId = 6,
                            Customers_LST_JOBName = "معلم"
                        },
                        new
                        {
                            Customers_LST_JOBId = 7,
                            Customers_LST_JOBName = "بازنشسته"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House", b =>
                {
                    b.Property<int>("House_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HouseCode_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_AB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Bargh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("House_DatePublish")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("House_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("House_Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Gaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("House_Image")
                        .HasColumnType("image");

                    b.Property<string>("House_Metrazh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_NumKahb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_NumTabagheh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_OtherEmkanat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Parking")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_PriceEjareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_PriceRahn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_StatusEjareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_StatusManzel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Tabagheh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_TypeDarb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("House_UserId")
                        .HasColumnType("int");

                    b.Property<string>("House_VoroodyType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_Id");

                    b.ToTable("Houses");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Ab", b =>
                {
                    b.Property<int>("House_LST_AbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_AbName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_AbId");

                    b.ToTable("House_LST_Abs");

                    b.HasData(
                        new
                        {
                            House_LST_AbId = 1,
                            House_LST_AbName = "دارد. مستقل"
                        },
                        new
                        {
                            House_LST_AbId = 2,
                            House_LST_AbName = "دارد. مشترک"
                        },
                        new
                        {
                            House_LST_AbId = 3,
                            House_LST_AbName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Bargh", b =>
                {
                    b.Property<int>("House_LST_BarghId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_BarghName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_BarghId");

                    b.ToTable("House_LST_Barghs");

                    b.HasData(
                        new
                        {
                            House_LST_BarghId = 1,
                            House_LST_BarghName = "دارد. مستقل"
                        },
                        new
                        {
                            House_LST_BarghId = 2,
                            House_LST_BarghName = "دارد. مشترک"
                        },
                        new
                        {
                            House_LST_BarghId = 3,
                            House_LST_BarghName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Darb", b =>
                {
                    b.Property<int>("House_LST_DarbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_DarbName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_DarbId");

                    b.ToTable("House_LST_Darbs");

                    b.HasData(
                        new
                        {
                            House_LST_DarbId = 1,
                            House_LST_DarbName = "حیاط - مستقل"
                        },
                        new
                        {
                            House_LST_DarbId = 2,
                            House_LST_DarbName = "حیاط - مشترک"
                        },
                        new
                        {
                            House_LST_DarbId = 3,
                            House_LST_DarbName = "ساختمان - مستقل"
                        },
                        new
                        {
                            House_LST_DarbId = 4,
                            House_LST_DarbName = "ساختمان - مشترک"
                        },
                        new
                        {
                            House_LST_DarbId = 5,
                            House_LST_DarbName = "نبش"
                        },
                        new
                        {
                            House_LST_DarbId = 6,
                            House_LST_DarbName = "دونبش"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Ejareh", b =>
                {
                    b.Property<int>("House_LST_EjarehId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_EjarehName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_EjarehId");

                    b.ToTable("House_LST_Ejarehs");

                    b.HasData(
                        new
                        {
                            House_LST_EjarehId = 1,
                            House_LST_EjarehName = "دارد"
                        },
                        new
                        {
                            House_LST_EjarehId = 2,
                            House_LST_EjarehName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Gaz", b =>
                {
                    b.Property<int>("House_LST_GazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_GazName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_GazId");

                    b.ToTable("House_LST_Gazs");

                    b.HasData(
                        new
                        {
                            House_LST_GazId = 1,
                            House_LST_GazName = "دارد. مستقل"
                        },
                        new
                        {
                            House_LST_GazId = 2,
                            House_LST_GazName = "دارد. مشترک"
                        },
                        new
                        {
                            House_LST_GazId = 3,
                            House_LST_GazName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_NumKhab", b =>
                {
                    b.Property<int>("House_LST_NumKhabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_NumKhabName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_NumKhabId");

                    b.ToTable("House_LST_NumKhabs");

                    b.HasData(
                        new
                        {
                            House_LST_NumKhabId = 1,
                            House_LST_NumKhabName = "1"
                        },
                        new
                        {
                            House_LST_NumKhabId = 2,
                            House_LST_NumKhabName = "2"
                        },
                        new
                        {
                            House_LST_NumKhabId = 3,
                            House_LST_NumKhabName = "3"
                        },
                        new
                        {
                            House_LST_NumKhabId = 4,
                            House_LST_NumKhabName = "4"
                        },
                        new
                        {
                            House_LST_NumKhabId = 5,
                            House_LST_NumKhabName = "5"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Parking", b =>
                {
                    b.Property<int>("House_LST_ParkingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_ParkingName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_ParkingId");

                    b.ToTable("House_LST_Parkings");

                    b.HasData(
                        new
                        {
                            House_LST_ParkingId = 1,
                            House_LST_ParkingName = "دارد"
                        },
                        new
                        {
                            House_LST_ParkingId = 2,
                            House_LST_ParkingName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Status", b =>
                {
                    b.Property<int>("House_LST_StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_StatusId");

                    b.ToTable("House_LST_Statuses");

                    b.HasData(
                        new
                        {
                            House_LST_StatusId = 1,
                            House_LST_StatusName = "تخلیه شده"
                        },
                        new
                        {
                            House_LST_StatusId = 2,
                            House_LST_StatusName = "در حال تخلیه"
                        },
                        new
                        {
                            House_LST_StatusId = 3,
                            House_LST_StatusName = "خالی"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Tabagheh", b =>
                {
                    b.Property<int>("House_LST_TabaghehId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_TabaghehName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_TabaghehId");

                    b.ToTable("House_LST_Tabaghehs");

                    b.HasData(
                        new
                        {
                            House_LST_TabaghehId = 1,
                            House_LST_TabaghehName = "1"
                        },
                        new
                        {
                            House_LST_TabaghehId = 2,
                            House_LST_TabaghehName = "2"
                        },
                        new
                        {
                            House_LST_TabaghehId = 3,
                            House_LST_TabaghehName = "3"
                        },
                        new
                        {
                            House_LST_TabaghehId = 4,
                            House_LST_TabaghehName = "4"
                        },
                        new
                        {
                            House_LST_TabaghehId = 5,
                            House_LST_TabaghehName = "5"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.House_LST_Voroody", b =>
                {
                    b.Property<int>("House_LST_VoroodyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("House_LST_VoroodyName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("House_LST_VoroodyId");

                    b.ToTable("House_LST_Voroodies");

                    b.HasData(
                        new
                        {
                            House_LST_VoroodyId = 1,
                            House_LST_VoroodyName = "مستقل"
                        },
                        new
                        {
                            House_LST_VoroodyId = 2,
                            House_LST_VoroodyName = "مشترک"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceID")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinceID");

                    b.ToTable("Provinces");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop", b =>
                {
                    b.Property<int>("Shop_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ShopCode_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_AB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Anbary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Asansor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Balakon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_BalakonMetrazh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Bargh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_BeARZ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Shop_DatePublish")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Shop_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("Shop_Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Gaz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_HagheCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Shop_Image")
                        .HasColumnType("image");

                    b.Property<string>("Shop_InsidePooshesh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Metrazh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Mougheyat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_PayaneKar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_PriceCharge")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_PriceEjareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_PriceRahn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Shoofazh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_StatusEjareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Status_Rah_OR_Ejareh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Tell")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_TypeDarb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_TypeSenf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shop_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Shop_UserId")
                        .HasColumnType("int");

                    b.HasKey("Shop_Id");

                    b.ToTable("Shops");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_AB", b =>
                {
                    b.Property<int>("Shop_LST_ABId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_ABName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_ABId");

                    b.ToTable("Shop_LST_ABs");

                    b.HasData(
                        new
                        {
                            Shop_LST_ABId = 1,
                            Shop_LST_ABName = "دارد"
                        },
                        new
                        {
                            Shop_LST_ABId = 2,
                            Shop_LST_ABName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Anbary", b =>
                {
                    b.Property<int>("Shop_LST_AnbaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_AnbaryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_AnbaryId");

                    b.ToTable("Shop_LST_Anbaries");

                    b.HasData(
                        new
                        {
                            Shop_LST_AnbaryId = 1,
                            Shop_LST_AnbaryName = "دارد"
                        },
                        new
                        {
                            Shop_LST_AnbaryId = 2,
                            Shop_LST_AnbaryName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Asansor", b =>
                {
                    b.Property<int>("Shop_LST_AsansorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_AsansorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_AsansorId");

                    b.ToTable("Shop_LST_Asansors");

                    b.HasData(
                        new
                        {
                            Shop_LST_AsansorId = 1,
                            Shop_LST_AsansorName = "دارد"
                        },
                        new
                        {
                            Shop_LST_AsansorId = 2,
                            Shop_LST_AsansorName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Balakon", b =>
                {
                    b.Property<int>("Shop_LST_BalakonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_BalakonName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_BalakonId");

                    b.ToTable("Shop_LST_Balakons");

                    b.HasData(
                        new
                        {
                            Shop_LST_BalakonId = 1,
                            Shop_LST_BalakonName = "دارد"
                        },
                        new
                        {
                            Shop_LST_BalakonId = 2,
                            Shop_LST_BalakonName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Bargh", b =>
                {
                    b.Property<int>("Shop_LST_BarghId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_BarghName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_BarghId");

                    b.ToTable("Shop_LST_Barghs");

                    b.HasData(
                        new
                        {
                            Shop_LST_BarghId = 1,
                            Shop_LST_BarghName = "دارد"
                        },
                        new
                        {
                            Shop_LST_BarghId = 2,
                            Shop_LST_BarghName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Darb", b =>
                {
                    b.Property<int>("Shop_LST_DarbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_DarbName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_DarbId");

                    b.ToTable("Shop_LST_Darbs");

                    b.HasData(
                        new
                        {
                            Shop_LST_DarbId = 1,
                            Shop_LST_DarbName = "شیشه ای"
                        },
                        new
                        {
                            Shop_LST_DarbId = 2,
                            Shop_LST_DarbName = "کرکره ای"
                        },
                        new
                        {
                            Shop_LST_DarbId = 3,
                            Shop_LST_DarbName = "آهنی"
                        },
                        new
                        {
                            Shop_LST_DarbId = 4,
                            Shop_LST_DarbName = "آلومینیوم"
                        },
                        new
                        {
                            Shop_LST_DarbId = 5,
                            Shop_LST_DarbName = "چوبی"
                        },
                        new
                        {
                            Shop_LST_DarbId = 6,
                            Shop_LST_DarbName = "پلاستیک فشرده"
                        },
                        new
                        {
                            Shop_LST_DarbId = 7,
                            Shop_LST_DarbName = "پرده"
                        },
                        new
                        {
                            Shop_LST_DarbId = 8,
                            Shop_LST_DarbName = "درب  برقی هوشمند"
                        },
                        new
                        {
                            Shop_LST_DarbId = 9,
                            Shop_LST_DarbName = "فلزی"
                        },
                        new
                        {
                            Shop_LST_DarbId = 10,
                            Shop_LST_DarbName = "سایر"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Ejareh", b =>
                {
                    b.Property<int>("Shop_LST_EjarehId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_EjarehName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_EjarehId");

                    b.ToTable("Shop_LST_Ejarehs");

                    b.HasData(
                        new
                        {
                            Shop_LST_EjarehId = 1,
                            Shop_LST_EjarehName = "دارد"
                        },
                        new
                        {
                            Shop_LST_EjarehId = 2,
                            Shop_LST_EjarehName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Gaz", b =>
                {
                    b.Property<int>("Shop_LST_GazId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_GazName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_GazId");

                    b.ToTable("Shop_LST_Gazs");

                    b.HasData(
                        new
                        {
                            Shop_LST_GazId = 1,
                            Shop_LST_GazName = "دارد"
                        },
                        new
                        {
                            Shop_LST_GazId = 2,
                            Shop_LST_GazName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_HagheCharge", b =>
                {
                    b.Property<int>("Shop_LST_HagheChargeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_HagheChargeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_HagheChargeId");

                    b.ToTable("Shop_LST_HagheCharges");

                    b.HasData(
                        new
                        {
                            Shop_LST_HagheChargeId = 1,
                            Shop_LST_HagheChargeName = "دارد"
                        },
                        new
                        {
                            Shop_LST_HagheChargeId = 2,
                            Shop_LST_HagheChargeName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_InsideDesign", b =>
                {
                    b.Property<int>("Shop_LST_InsideDesignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_InsideDesignName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_InsideDesignId");

                    b.ToTable("Shop_LST_InsideDesigns");

                    b.HasData(
                        new
                        {
                            Shop_LST_InsideDesignId = 1,
                            Shop_LST_InsideDesignName = "سرامیک"
                        },
                        new
                        {
                            Shop_LST_InsideDesignId = 2,
                            Shop_LST_InsideDesignName = "آجری"
                        },
                        new
                        {
                            Shop_LST_InsideDesignId = 3,
                            Shop_LST_InsideDesignName = "بتنی"
                        },
                        new
                        {
                            Shop_LST_InsideDesignId = 4,
                            Shop_LST_InsideDesignName = "خشت و گل"
                        },
                        new
                        {
                            Shop_LST_InsideDesignId = 5,
                            Shop_LST_InsideDesignName = "گچی"
                        },
                        new
                        {
                            Shop_LST_InsideDesignId = 6,
                            Shop_LST_InsideDesignName = "سیمانی"
                        },
                        new
                        {
                            Shop_LST_InsideDesignId = 7,
                            Shop_LST_InsideDesignName = "کاغذ دیواری"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Location", b =>
                {
                    b.Property<int>("Shop_LST_LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_LocationName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_LocationId");

                    b.ToTable("Shop_LST_Locations");

                    b.HasData(
                        new
                        {
                            Shop_LST_LocationId = 1,
                            Shop_LST_LocationName = "تجاری"
                        },
                        new
                        {
                            Shop_LST_LocationId = 2,
                            Shop_LST_LocationName = "داخل پاساژ"
                        },
                        new
                        {
                            Shop_LST_LocationId = 3,
                            Shop_LST_LocationName = "بیرون پاساژ"
                        },
                        new
                        {
                            Shop_LST_LocationId = 4,
                            Shop_LST_LocationName = "داخل مجتمع"
                        },
                        new
                        {
                            Shop_LST_LocationId = 5,
                            Shop_LST_LocationName = "بیرون مجتمع"
                        },
                        new
                        {
                            Shop_LST_LocationId = 6,
                            Shop_LST_LocationName = "داخل گاراژ"
                        },
                        new
                        {
                            Shop_LST_LocationId = 7,
                            Shop_LST_LocationName = "بیرون گاراژ"
                        },
                        new
                        {
                            Shop_LST_LocationId = 8,
                            Shop_LST_LocationName = "داخل کوچه"
                        },
                        new
                        {
                            Shop_LST_LocationId = 9,
                            Shop_LST_LocationName = "سر کوچه"
                        },
                        new
                        {
                            Shop_LST_LocationId = 10,
                            Shop_LST_LocationName = "بر خیابان"
                        },
                        new
                        {
                            Shop_LST_LocationId = 11,
                            Shop_LST_LocationName = "سر خیابان"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_PayaneKar", b =>
                {
                    b.Property<int>("Shop_LST_PayaneKarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_PayaneKarName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_PayaneKarId");

                    b.ToTable("Shop_LST_PayaneKars");

                    b.HasData(
                        new
                        {
                            Shop_LST_PayaneKarId = 1,
                            Shop_LST_PayaneKarName = "دارد"
                        },
                        new
                        {
                            Shop_LST_PayaneKarId = 2,
                            Shop_LST_PayaneKarName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Rahn_OR_Ejareh", b =>
                {
                    b.Property<int>("Shop_LST_Rahn_OR_EjarehId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_Rahn_OR_EjarehName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_Rahn_OR_EjarehId");

                    b.ToTable("Shop_LST_Rahn_OR_Ejarehs");

                    b.HasData(
                        new
                        {
                            Shop_LST_Rahn_OR_EjarehId = 1,
                            Shop_LST_Rahn_OR_EjarehName = "رهن کامل"
                        },
                        new
                        {
                            Shop_LST_Rahn_OR_EjarehId = 2,
                            Shop_LST_Rahn_OR_EjarehName = "رهن موقت"
                        },
                        new
                        {
                            Shop_LST_Rahn_OR_EjarehId = 3,
                            Shop_LST_Rahn_OR_EjarehName = "اجاره موقت"
                        },
                        new
                        {
                            Shop_LST_Rahn_OR_EjarehId = 4,
                            Shop_LST_Rahn_OR_EjarehName = "رهن و اجاره"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Senf", b =>
                {
                    b.Property<int>("Shop_LST_SenfId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_SenfName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_SenfId");

                    b.ToTable("Shop_LST_Senfs");

                    b.HasData(
                        new
                        {
                            Shop_LST_SenfId = 1,
                            Shop_LST_SenfName = "قطعات یدکی خودرو سبک"
                        },
                        new
                        {
                            Shop_LST_SenfId = 2,
                            Shop_LST_SenfName = "قطعات یدکی خودرو سنگین"
                        },
                        new
                        {
                            Shop_LST_SenfId = 3,
                            Shop_LST_SenfName = "قطعات یدکی موتورسیکلت"
                        },
                        new
                        {
                            Shop_LST_SenfId = 4,
                            Shop_LST_SenfName = "خدمات برق و باتری"
                        },
                        new
                        {
                            Shop_LST_SenfId = 5,
                            Shop_LST_SenfName = "خدمات روغن و مکانیکی"
                        },
                        new
                        {
                            Shop_LST_SenfId = 6,
                            Shop_LST_SenfName = "خدمات لاستیک خودرو"
                        },
                        new
                        {
                            Shop_LST_SenfId = 7,
                            Shop_LST_SenfName = "خدمات ماشین های اداری"
                        },
                        new
                        {
                            Shop_LST_SenfId = 8,
                            Shop_LST_SenfName = "خدمات کافی نت، گیم نت"
                        },
                        new
                        {
                            Shop_LST_SenfId = 9,
                            Shop_LST_SenfName = "خدمات درب و پنجره"
                        },
                        new
                        {
                            Shop_LST_SenfId = 10,
                            Shop_LST_SenfName = "سایر خدمات"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Shoofazh", b =>
                {
                    b.Property<int>("Shop_LST_ShoofazhId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_ShoofazhName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_ShoofazhId");

                    b.ToTable("Shop_LST_Shoofazhs");

                    b.HasData(
                        new
                        {
                            Shop_LST_ShoofazhId = 1,
                            Shop_LST_ShoofazhName = "دارد"
                        },
                        new
                        {
                            Shop_LST_ShoofazhId = 2,
                            Shop_LST_ShoofazhName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Shop_LST_Tell", b =>
                {
                    b.Property<int>("Shop_LST_TellId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Shop_LST_TellName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Shop_LST_TellId");

                    b.ToTable("Shop_LST_Tells");

                    b.HasData(
                        new
                        {
                            Shop_LST_TellId = 1,
                            Shop_LST_TellName = "دارد"
                        },
                        new
                        {
                            Shop_LST_TellId = 2,
                            Shop_LST_TellName = "ندارد"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Willing", b =>
                {
                    b.Property<int>("Willing_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Willing_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Willing_DatePublish")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Willing_Delete")
                        .HasColumnType("bit");

                    b.Property<string>("Willing_Family")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Willing_Image")
                        .HasColumnType("image");

                    b.Property<string>("Willing_JahatList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Willing_KhahanList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Willing_Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Willing_Moshakhasat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Willing_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Willing_Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Willing_Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Willing_UserId")
                        .HasColumnType("int");

                    b.HasKey("Willing_Id");

                    b.ToTable("Willings");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Willing_LST", b =>
                {
                    b.Property<int>("Willing_LSTId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Willing_LSTName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Willing_LSTId");

                    b.ToTable("Willing_LSTs");

                    b.HasData(
                        new
                        {
                            Willing_LSTId = 1,
                            Willing_LSTName = "یک واحد آپارتمان"
                        },
                        new
                        {
                            Willing_LSTId = 2,
                            Willing_LSTName = "یک باب مغازه"
                        },
                        new
                        {
                            Willing_LSTId = 3,
                            Willing_LSTName = "یک باب منزل ویلایی"
                        },
                        new
                        {
                            Willing_LSTId = 4,
                            Willing_LSTName = "یک قطعه زمین"
                        });
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Willing_LST_Jahat", b =>
                {
                    b.Property<int>("Willing_LST_JahatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Willing_LST_JahatName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Willing_LST_JahatId");

                    b.ToTable("Willing_LST_Jahats");

                    b.HasData(
                        new
                        {
                            Willing_LST_JahatId = 1,
                            Willing_LST_JahatName = "رهن"
                        },
                        new
                        {
                            Willing_LST_JahatId = 2,
                            Willing_LST_JahatName = "رهن و اجاره"
                        },
                        new
                        {
                            Willing_LST_JahatId = 3,
                            Willing_LST_JahatName = "خرید"
                        },
                        new
                        {
                            Willing_LST_JahatId = 4,
                            Willing_LST_JahatName = "فروش"
                        },
                        new
                        {
                            Willing_LST_JahatId = 5,
                            Willing_LST_JahatName = "معاوضه"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("ZagrosRealState.Data.Models.Data.ApplicationRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ZagrosRealState.Data.Models.Data.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ZagrosRealState.Data.Models.Data.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("ZagrosRealState.Data.Models.Data.ApplicationRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ZagrosRealState.Data.Models.Data.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ZagrosRealState.Data.Models.Data.ApplicationUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Apartment_LST_EmkanatSatus", b =>
                {
                    b.HasOne("ZagrosRealState.Entities.Entities.Apartment", "Entity_Aparteman")
                        .WithMany()
                        .HasForeignKey("Entity_ApartemanApartment_Id");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Cities", b =>
                {
                    b.HasOne("ZagrosRealState.Entities.Entities.Province", "Province")
                        .WithMany("Cities")
                        .HasForeignKey("ProvinceID");
                });

            modelBuilder.Entity("ZagrosRealState.Entities.Entities.Customers", b =>
                {
                    b.HasOne("ZagrosRealState.Entities.Entities.Cities", "Cities")
                        .WithMany("Customers")
                        .HasForeignKey("CitiesCityID");
                });
#pragma warning restore 612, 618
        }
    }
}
